RssFeed/Models/ErrorViewModel.cs
namespace RssFeed.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

RssFeed/Models/Item.cs
namespace RssFeed.Models
{
    public class Item
    {
        public string? Title { get; set; }
        public DateTime Date { get; set; }
        public string? Description { get; set; }
        public string? Url { get; set; }
    }
}

RssFeed/Models/Settings.cs
namespace RssFeed.Models
{
    public class Settings
    {
        public bool DescriptionTags { get; set; }
        public string[] Url { get; set; } = new string[5];
        public int UpdateTime { get; set; }
    }
}

RssFeed/Controllers/FeedController.cs
using Microsoft.AspNetCore.Mvc;
using BL.Abstract;
using RssFeed.Models;
using RssFeed.Mappers;

namespace RssFeed.Controllers
{
    public class FeedController : Controller
    {
        private readonly IDownloadFeedService _download;
        private readonly IConfiguration _configuration;
        private readonly IFeedService _feedService;
        public FeedController(IDownloadFeedService download, IConfiguration configuration, IFeedService feedService)
        {
            _download = download;
            _configuration = configuration;
            _feedService = feedService;
        }
#nullable disable
        public async Task<IActionResult> RSS()
        {   
            List<Item> items = new List<Item>();
            var settings = HttpContext.Session.Get<Settings>("settings");
            settings = _feedService.ChooseSourceForSettings(settings?.FromAPIToBusiness()).FromBusinessToApi();


            if (settings.DescriptionTags == false)
            {
                ViewBag.Tags = "false";
            }
            else
            {
                ViewBag.Tags = "true";
            }
            ViewBag.UpdateTime = settings.UpdateTime * 60;

            var download = await _download.DownloadAsync(settings.Url);
            foreach (var item in download)
            {
                items.Add(item.FromBusinessToAPI());
            }
            return View(items);
        }
    }
}

RssFeed/Controllers/SettingsController.cs
using Microsoft.AspNetCore.Mvc;
using RssFeed.Models;
using System.Diagnostics;
using BL.Abstract;
using RssFeed.Mappers;


namespace RssFeed.Controllers
{
    public class SettingsController : Controller
    {
        private readonly ISettingsService _settingsService;
        private readonly Settings _settings;

        public SettingsController(Settings settings, ISettingsService settingsService)
        { 
            _settingsService = settingsService;
            _settings = settings;
        }

        public IActionResult Settings()
        {
            var settings = HttpContext.Session.Get<Settings>("settings");
            return View(settings);
        }
        
#nullable disable
        [HttpPost]
        public IActionResult Settings(Settings settings)
        {
            var BLsettings = _settingsService.SettingsValidation(settings.FromAPIToBusiness());

            _settings.DescriptionTags = BLsettings.DescriptionTags;
            _settings.UpdateTime = BLsettings.UpdateTime;
            _settings.Url = BLsettings.Url;

            HttpContext.Session.Set("settings", _settings);
            return RedirectToAction("Settings");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

RssFeed/Views/Feed/RSS.cshtml
@model IEnumerable<RssFeed.Models.Item>


@if (Model.Count() > 0)
{
    <head>
        <meta http-equiv="refresh" content="@ViewBag.UpdateTime">
        <title>RSS</title>
    </head>
    <body>
        <table class="table table-bordered table-striped" style="width:100%">
            <thead>
                <tr>
                    <th>
                        Дата публикации
                    </th>
                    <th>
                        Ссылка на статью
                    </th>
                    <th>
                        Описание
                    </th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td width="10%">@item.Date</td>
                        <td width="20%"><a href="@item.Url">@item.Title</a></td>
                        <td width="80%">
                            <details>
                                <summary>Раскрыть описание</summary>
                                @if (@ViewBag.Tags == "true")
                                {
                                    @Html.Raw(item.Description)
                                }
                                else
                                {
                                    @item.Description
                                }
                            </details>
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </body>

}
else
{
    <p>Записи отсутствуют</p>
}

RssFeed/Views/Settings/Settings.cshtml
@model RssFeed.Models.Settings

<form method="post" asp-action="Settings">

    <div>
        <span>RSS каналы</span> <br />
        <label>URL1</label>
        @if (Model != null && !String.IsNullOrEmpty(Model.Url[0]))
        {
            <input size="50" asp-for="Url[0]" type="text" value=@Model.Url[0]>

            <br />

            <br />
        }
        else
        {
            <input size="50" asp-for="Url[0]" type="text">

            <br />

            <br />
        }
        <label>URL2</label>
        @if (Model != null && !String.IsNullOrEmpty(Model.Url[1]))
        {
            <input size="50" asp-for="Url[1]" type="text" value=@Model.Url[1]>

            <br />

            <br />
        }
        else
        {
            <input size="50" asp-for="Url[1]" type="text">

            <br />

            <br />
        }
        <label>URL3</label>
        @if (Model != null && !String.IsNullOrEmpty(Model.Url[2]))
        {
            <input size="50" asp-for="Url[2]" type="text" value=@Model.Url[2]>

            <br />

            <br />
        }
        else
        {
            <input size="50" asp-for="Url[2]" type="text">

            <br />

            <br />
        }
        <label>URL4</label>
        @if (Model != null && !String.IsNullOrEmpty(Model.Url[3]))
        {
            <input size="50" asp-for="Url[3]" type="text" value=@Model.Url[3]>

            <br />

            <br />
        }
        else
        {
            <input size="50" asp-for="Url[3]" type="text">

            <br />

            <br />
        }
        <label>URL5</label>
        @if (Model != null && !String.IsNullOrEmpty(Model.Url[4]))
        {
            <input size="50" asp-for="Url[4]" type="text" value=@Model.Url[4]>

            <br />

            <br />
        }
        else
        {
            <input size="50" asp-for="Url[4]" type="text">

            <br />

            <br />
        }
    </div>

    <div>
        <label asp-for="UpdateTime">Частота обновления в минутах</label><br />
        @if (Model != null)
        {
            <input min="5" max="1440" asp-for="UpdateTime" type="number" value=@Model.UpdateTime>
        }
        else
        {
            <input min="5" max="1440" asp-for="UpdateTime" type="number">
        }
    </div>

    <div>
        <br />
        <input asp-for="DescriptionTags">
        <label asp-for="DescriptionTags">Описание в форматированном виде</label>
    </div>

    <div>
        <br />
        <button type="submit">Сохранить</button>
    </div>
</form>

RssFeed/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - RSS Feeder</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/RssFeed.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Settings" asp-action="Settings">RssFeed</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Settings" asp-action="Settings">Settings</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Feed" asp-action="RSS">RSS</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - RssFeed - <a asp-area="" asp-controller="Feed" asp-action="RSS">RSS</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>